### ISSUE TITLE
Is there any way to sync data with specified file (JSON)

### ISSUE THREAD

**Issue by Andrewyg** [manp/syncs#1]
I've look over this module (package) and the sample of object, or chatly. But it seems like it's just syncing data but every time you refresh it (if there is only you online) the data will be reset so I was wonder is there any code to let you sync to a database file like data.json and every time you modfy it it was synced to data.json, and the data you modify last time can be use in your next session

**Comment by manp** [comment]
A Syncs connection works only as a bridge between server and clients. It is persistent on network disconnect but when the page reloads, client will create new connection, in _chatly_ sample, user info are stored in client `data` property, so by creating new connection the last user info will be destroy. 
For this situation it depend on application logic and it's up to developer. I think there is three approach to handle this:

1. Store user data in `SharedObject` provided by Syncs framework but it's suitable for small pieces of data.
2. Create a session on server side, storing data (like chat history) on persistent database.
3. Storing data on client side persistent storages like `LocalStorage` , `SessionStorage` , `indexedDB` or `Web Sql` which are available in modern web browsers.

I'm working on a feature to pin a connection to restore connection on page reload.
Thank for your regard.👍

**Comment by Andrewyg** [comment]
I've look through your solution but it doesn't fit my usage I'm syncing something like post or collaborate note and it should be a huge data with time stamp , author detail so first on don't fit
Second session is not fit because user may change client 
Last I don't really know what's client storage but I do know it doesn't fit if your user will change client often
I think it'll be good if we can sync with SQL or json db, I'll figure it out
If there is a way that can sync with JSON notify me
Thanks a lor
